apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAAVAeX9zAtrBTLXkR0arh2fy8IH+cSDGcp7SM+xDHGY8+rfgps60dHTQl+EvEMn9z/JEeyztdP3HobZcHCP4ub5aYrbe6kGuVj1MG0VF4NIhK0sLp6JrytKpoXSBm7MNWNQPQIHWaAF/Sm3sqMpMqlCuR47YPkKmn2nOmC8XsFcKKHXbhThBiD9ufcAYwQgQr7kCzP03ysol8yRR9VNDBMUU1voAUiScEwbuwcFjnLgpa9COEY7txNev/61f9XLUjzhrM32S2KW78MhS5SbBI7cGYlWhmsZrPcRoyMmSOxJ3b2W3AKG0Pl/mQnVdlNk48PRiyq87FLupqv7v3owu0zlVUVOJNG9IOr+yfHLMB2hoCOvrGPgsIfnDk/gLfyj+nMDDcid6lpaA1fhpA7ecraOPPGC52k5+yQ+dHVD3z/WidFq/uHu0ok/g5xjbAYDBTaYY1g3RgLpv0hyiJ9XKt1kd8Wor8VwUyllipBc7BRMeSuqhdwGizTO0UqNw9D9m0qFYQG69yRdaj/D0Ol3KwYCRjPlQI1h+gqLnj35N3REPvpxgT6+sYbkvAb9Wk1yE0GylqtHnKr/6GjDspc0laWQsGT2pSIBONUFedNh1vNUiMl0w1VeweSh3CVwZv253Mgi0dC+ykDtYiO8Em7wF4rsU/hASV70e/vWHwaU5j4xSRSUvPMBAZqyOmiTmvkKOKStpAh2TxIIZI5BEmoSn2xjgMLhCqa0bGVFuDx70iQXks5/sMq76opWDiOhMaMrrIkkUP2kd14j8VHI0TFsXZvyfvPbi7bBoog/15495gtysGWfuMbTKAFhkgzg0qoSPxJEFUHxrKaV03Zn7VMmuvTF63rHqQYjo9dblWTxdisx8rWFlrfYJUX/Cn6RHrJnaxcVI1oMOBRX533Nbu6kD5EJqmx/BwzV3L/UdwocZIiJt4Y03cokY22teFiVzjROrhR/iH6RhbRiqt4sNVDGyPUByjii6YyhSEP+igJsECidqffa81YwF6oPmDrTxBRurrdB/Zkk7u+y3G3XGgylm3dIjBsns8Wl8rapejbnfgGSWdd8lE9u71Rs7Y36Lb8FL8DegYsfUwap+xmBINLNQWa5cQaHFEW356bSrf6KJ70qDzqBWbYgBbOcp3s1sEZX3eckmycl0d2QudhXu7rdQccd12PWaIY2Ew0phpzaQZ23G8QkcMU6t/mdJ0bwRqYtE3nQywd0XDgN/96CHVcBSHYOH5Is3Vkl62cWk8J+umaCEUq8DUasVLSEjQTFUxBhptU6xqVymimc1SRgwuiEW5OXeocnGyyRaM6oGwK5AVr13Lw+ACrCEd4v+gHsZq52s8U
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

